_target_: experiment.WeightVirtualization

model_file: 'pretrained_models/fff/sc_bestacc.pt'
# fim_file: 'data/fim/fim_sc.pt'
fim_file: null
page_size: 2 # Page size w/ 5 options: s, m, l, xl, xxl
search_type: greedy_randomleafsplit # greedy_base, greedy_expand, greedy_random, greedy_fisher
kappa: 0.0 # matching reg.
n_splits: 2 # For splitted leaf matching
amount: 0.5
weights_per_page: null
n_virtualpages: null
mlflow_id: 0
only_generate_fim: 0
